    # Use the official Node.js image as the base image
    FROM node:24.14.0-slim

    RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

    # Set the working directory inside the container
    WORKDIR /usr/src/app

    # Copy package.json and package-lock.json to the working directory
    COPY package*.json ./

    # Install the application dependencies
    RUN npm install

    # Copy the rest of the application files
    COPY . .

    # Expose the application port
    EXPOSE 3000

    # Command to run the application
    CMD ["npm", "run", "start:dev"]