FROM node:24.14.0-slim

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Gera o Prisma Client, Aplica as Migrations e Inicia o NestJS
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && exec npm run start:dev"]
